# version: 2
# jobs:
#   build:
#     docker:
#       - image: circleci/python:3.6.4
# #    working_directory: ~/project
# #    machine: true
#     steps:
#       - checkout
#       - run: ls -l
#       - run:
#           command: |  # use pipenv to install dependencies
#              sudo pip3 install requests
#              sudo pip3 install click
#       - run: python3 docker-auto.py
# workflows:
#   version: 2
#   test_workflows: #name of workflows
#     jobs:
#       - build
#       #- build2:      # only id we build2
#        #   requires:  # if build 2 depend on build 1 so do this
#         #   - build
        
        
# #       - run: docker-compose up -d
# #       - run: docker ps 
# #       - run: ls -l
version: 2.1
executors:
  exec_env:
    docker:
        - image: ubuntu:latest
jobs:
  build:
    executor: exec_env
    steps:
      - checkout
      - run: apt-get update -yqq
      - run: apt-get install software-properties-common -yqq
      - run: add-apt-repository ppa:deadsnakes/ppa -y
      - run: apt-get update -yqq
      - run: apt-get install python3.8 -yqq
      - run: apt-get install curl -yqq
      - run: curl ifconfig.co
      
workflows:
  version: 2
  test_workflows: #name of workflows
    jobs:
      - build
      #- build2:      # only id we build2
       #   requires:  # if build 2 depend on build 1 so do this
        #   - build
