version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
#      - image: circleci/python:3.7.4
    working_directory: ~/project
#    machine: true
#    machine:
#      python:
#       version: 3.5.2
    steps:
#       - checkout
#       - run: docker-compose up -d
#       - run: docker ps 
#       - run: ls -l
       - run: sudo apt-get install python3-pip
#       - run: sudo pip3 install requests
#       - run: sudo pip3 install click
#       - run: ls -l
#       - run: python3 docker-auto.py
       

workflows:
  version: 2
  test_workflows: #name of workflows
    jobs:
      - build
      #- build2:      # only id we build2
       #   requires:  # if build 2 depend on build 1 so do this
        #   - build
