version: 2.1
executors:
  exec_env:
    docker:
      - image: ubuntu:latest
    environment:
      RELEAI_ORG_NAME: qa100
commands:
  setup:
    description: "Prepare executor env"
    steps:
      - checkout
      - run: apt-get update -yqq
      - run: apt-get install software-properties-common -yqq
      - run: add-apt-repository ppa:deadsnakes/ppa -y
      - run: apt-get update -yqq
      - run: apt-get install python3-pip -yqq
      - run: apt-get install python3.8 -yqq
      - run: apt-get install curl -yqq
      - run: apt-get install docker-compose -yqq
      - run: pip3 install requests
      - run: curl ifconfig.co
jobs:
  build:
    executor: exec_env
    steps:
      - setup
      - run: ls -l
      - run: python3 docker-auto.py
workflows:
  version: 2
  setup_build:
    jobs:
      - build:
          filters:
            branches: 
              only: master

#       - setup # step1
#       - build: # step2
#           requires: 
#            - setup # must to finish step1 to progress
#           filters:
#             branches:
#               only: master # work only on master
