version: 2
jobs:
  build:
    docker:
     # using custom image, see .circleci/images/primary/Dockerfile
       - image: circleci/python:3.6.4
    #working_directory: ~/Saar1122/test
    #machine: true
    steps:
#       - checkout
#       - run: docker-compose up -d
#       - run: docker ps 
#       - run: ls -l
       - run: pip3 install requests
       - run: pip3 install click
       - run: pip3 docker-auto.py
       
workflows:
  version: 2
  build-deploy:
    jobs:
      - build 
      - deploy-job:
          requires:
            - build # Only deploy once the build job has completed
          filters:
            branches:
              only: master # Only deploy on the master branch
