version: 2
jobs:
  build:
    docker:
      - image: ubuntu:latest
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: "Switch to Python v3.7"
          command: |
            pip install pipenv
            pipenv install
#      - run: pip3 install requests
#      - run: pip3 install click
      - run: ls -l
      - run: python3 docker-auto.py
workflows:
  version: 2
  test_workflows: #name of workflows
    jobs:
      - build
      #- build2:      # only id we build2
       #   requires:  # if build 2 depend on build 1 so do this
        #   - build
        
        
#       - run: docker-compose up -d
#       - run: docker ps 
#       - run: ls -l
