
version: 2
jobs:
 build:
   working_directory: ~/demo-project
   machine: true
   steps:
     - checkout
     # build image with dockefile
     - run: docker-auto.py

#      - run: docker build . -t saar
#      # build the application image
#      - run: docker run -p 3000:3000 -d saar
#      # check containter id
#      - run: docker ps -a
     
