
version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     # build image with dockefile
     - run: docker build . -t saar
     # build the application image
     - run: docker run -p 3000:3000 -d saar
     - run: docker ps -a
