version: 2
jobs:
  build:
    #docker:
     # using custom image, see .circleci/images/primary/Dockerfile
     #- image: circleci/node:7.10
    #working_directory: ~/Saar1122/test
    machine: true
    steps:
      - checkout
      - run: docker-compose up
      - run: docker ps 
workflows:
  version: 2
  build-deploy:
    jobs:
      - build 
      - deploy-job:
          requires:
            - build # Only deploy once the build job has completed
          filters:
            branches:
              only: master # Only deploy on the master branch
