version: 2.1
executors:
  exec_env:
    docker:
      - image: ubuntu:latest
    environment:
      RELEAI_ORG_NAME: qa100
commands:
  setup:
    description: "Prepare executor env"
    steps:
      - checkout
      - run: apt-get update -yqq
      - run: apt-get install software-properties-common -yqq
      - run: add-apt-repository ppa:deadsnakes/ppa -y
      - run: apt-get update -yqq
      - run: apt-get install python3-pip -yqq
      - run: apt-get install python3.8 -yqq
      - run: apt-get install curl -yqq
      - run: apt-get remove docker docker-engine docker.io -yqq
      - run: apt install apt-transport-https ca-certificates curl software-properties-common -yqq
      - run: apt-get install docker-compose -yqq
      #- run: apt-cache policy docker-ce
      - run: apt install docker.io -yqq
      - run: systemctl start docker
      - run: systemctl enable docker
      - run: pip3 install requests
      - run: pip3 install click
      - run: curl ifconfig.co
jobs:
  build:
    executor: exec_env
    steps:
      - setup
      - run: ls -l
      - run: docker build . -t saar
      - run: docker run -p 3000:3000 -d saar
      - run: curl localhost:3000
workflows:
  version: 2
  setup_build:
    jobs:
      - build:
          filters:
            branches: 
              only: dev

#       - setup # step1
#       - build: # step2
#           requires: 
#            - setup # must to finish step1 to progress
#           filters:
#             branches:
#               only: master # work only on master
