version: 2.1
executors:
  exec_env:
    docker:
        - image: ubuntu:latest
jobs:
  setup:
    executor: exec_env
    steps:
      - checkout
      - run: apt-get update -yqq
      - run: apt-get install software-properties-common -yqq
      - run: add-apt-repository ppa:deadsnakes/ppa -y
      - run: apt-get update -yqq
      - run: apt-get install python3.8 -yqq
      - run: apt-get install curl -yqq
      - run: curl ifconfig.co
   build:
    executor: exec_env
    steps:
      - run: docker-compose up -d
        
workflows:
  version: 2
  setup_build: #name of workflows
    jobs:
      - setup:
        requires:
        - build
 #          - test
      #- build2:      # only id we build2
       #   requires:  # if build 2 depend on build 1 so do this
        #   - build
