version: 2.1
executors:
  exec_env:
    docker:
        - image: ubuntu:latest
#        - image: circleci/python:latest
jobs:
  setup:
    executor: exec_env
    steps:
      - checkout
      - run: apt-get update -yqq
      - run: apt-get install software-properties-common -yqq
      - run: add-apt-repository ppa:deadsnakes/ppa -y
      - run: apt-get update -yqq
      - run: apt-get install python3-pip -yqq
      - run: apt-get install python3.8 -yqq
      - run: apt-get install curl -yqq
      - run: apt-get install docker-compose -yqq
      - run: pip3 install requests
      - run: curl ifconfig.co
      - run: ls -l
#      - run: python3 docker-auto.py
  build:
    executor: exec_env
    steps:
      - checkout
      - run: ls -l
      - run: python3 docker-auto.py
        
workflows:
  version: 2
  setup_build: #name of workflows
    jobs:
      - setup
      - build:
          requires:
           - setup
          filters:
            branches:
              only:
               - dev
