version: 2.1
executors:
  exec_env:
    docker:
      - image: ubuntu:latest
    environment:
      RELEAI_ORG_NAME: qa100
commands:
  setup:
    description: "Prepare executor env"
    steps:
      - checkout
      - setup_remote_docker
      - run: 
          name: Install ubuntu updates
          command: |
             apt-get update -yqq
             apt-get install software-properties-common -yqq
             add-apt-repository ppa:deadsnakes/ppa -y
             apt-get update -yqq
      - run: apt-get install curl -yqq
      - run: 
          name: Installing Docker packages
          command: |
             apt-get update --fix-missing
             apt-get install -y apt-transport-https ca-certificates software-properties-common
             curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
             apt-key fingerprint 0EBFCD88
             add-apt-repository \
               "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
               $(lsb_release -cs) \
               stable"
             apt-get update
             apt-get install -y docker-ce
             set -x
             curl -L https://github.com/docker/compose/releases/download/1.25.3/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
             chmod +x /usr/local/bin/docker-compose
      - run:
          name: Install Pip3 + python requirements
          command: |
             apt-get install python3-pip -yqq
             apt-get install python3.8 -yqq
      - run: 
          name: Install Python Packages
          command: |
             pip3 install requests
             pip3 install click
      - run: curl ifconfig.co
jobs:
  build:
    executor: exec_env
    steps:
      - setup
      - run: ls -l
      - run: python3 docker-auto.py
      - run: docker ps
      - run: docker build . -t saar
      - run: docker run -p 5000:5000 -d saar
      - run: docker ps
workflows:
  version: 2
  setup_build:
    jobs:
      - build:
          filters:
            branches: 
              only: dev
