version: 2
jobs:
  build:
    docker:
     # using custom image, see .circleci/images/primary/Dockerfile
       - image: circleci/python:3.6.4
    working_directory: ~/project
    branches:
       only:
          - develop
    #machine: true
    steps:
#       - checkout
#       - run: docker-compose up -d
#       - run: docker ps 
#       - run: ls -l
       - run: sudo pip3 install requests
       - run: sudo pip3 install click
       - run: ls -l
#      - run: python3 docker-auto.py
       

workflows:
  version: 2
  build:
    jobs:
      - build
